services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - CHROMA_URL=${CHROMA_URL}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - EMBEDDING_API_KEY=${EMBEDDING_API_KEY}
      - PORT=${PORT}